### ISSUE TITLE
Feature Request: Optional variable input, docker-compose extra structure

### ISSUE THREAD

**Issue by voryzen** [VivumLab/VivumLab#111]
Allows the addition of extra detailing/structure/information/environmental variables/whatever is required by use of an ansible include var (like labels.j2 include)

**Comment by denis-ev** [comment]
Question on stackoverflow.com
https://stackoverflow.com/questions/65380329/how-to-pass-variables-to-jinja2-2-11-x-include-context

**Comment by codefriar** [comment]
@voryzen @denis-ev 

I wanted to start work on our oldest issues but I'm having a hard time understanding what this one is. can either of you explain more?

**Comment by denis-ev** [comment]
https://stackoverflow.com/questions/65380329/how-to-pass-variables-to-jinja2-2-11-x-include-context
