### ISSUE TITLE
Feature Request: Adding command to change the settings folder 

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#124]
**Describe the solution you'd like**
running `vlab [any command] --settings [folder name]` or similar
The main purpose would be for devs to check and test on testing servers, without changing the git and keeping their prod server settings in place.

**Describe alternatives you've considered**
manually renaming the settings folder every time you test something

What do you think about this? @voryzen

**Comment by robjloranger** [comment]
I like this idea. Currently I keep two copies of the repo, one for testing and dev and one for my production server.

**Comment by voryzen** [comment]
Yea, this would actually be a pretty welcome feature for devs.

You could use the existing taskit and a good helper function, and this would not create a real heavy rewrite

**Comment by voryzen** [comment]
What was the issue again?

Can we post the issues, and code examples/output etc.. here on github?

**Comment by denis-ev** [comment]
https://github.com/VivumLab/VivumLab/pull/133#issuecomment-720031172

**Comment by voryzen** [comment]
> [#133 (comment)](https://github.com/VivumLab/VivumLab/pull/133#issuecomment-720031172)

haha, I was looking in zulip. cheers
