### ISSUE TITLE
Bug: docker-compose is already installed with system packages on Debian

### ISSUE THREAD

**Issue by robjloranger** [VivumLab/VivumLab#127]
**Describe the bug**
During setup on the host, task `Install Docker-compose`, fails becuase it was already installed during the previous step to install Docker and containerd.

**To Reproduce**
1. Fresh server with Debian 10
2. Configure vlab
3. Deploy

**Expected behavior**
Should not attempt to install docker-compose on Debian

**Desktop (please complete the following information):**
 - OS: Debian 10.6
 - Service: n/a
 - Vivumlab Version: v0.3.0

**Additional context**
Error:
```
TASK [vivumlab_setup : Install Docker-compose] ***********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: u'pkg_resources' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused.
fatal: [myserver]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (setuptools) on earthship's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by voryzen** [comment]
awaiting on the output of:
`python --version`
`whereis python`
