### ISSUE TITLE
Bug: Do not use the wireguard PPA

### ISSUE THREAD

**Issue by robjloranger** [VivumLab/VivumLab#128]
**Describe the bug**
The wireguard PPA is no longer maintained/active and results in a 404 during task `Add the WireGuard PPA repository`.

**To Reproduce**
1. Debian 10 server
2. Configure
3. Deploy

**Expected behavior**
This step should no longer exist. See [https://launchpad.net/~wireguard](https://launchpad.net/~wireguard) for reference.

**Desktop (please complete the following information):**
 - OS: Debian 10.6
 - Service: n/a
 - Vivumlab Version: v0.3.0

**Additional context**
Error:
```
TASK [vivumlab_wireguard : Add the WireGuard PPA repository] *********************************************
FAILED - RETRYING: Add the WireGuard PPA repository (10 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (9 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (8 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (7 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (6 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (5 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (4 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (3 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (2 retries left).
FAILED - RETRYING: Add the WireGuard PPA repository (1 retries left).
fatal: [myserver]: FAILED! => {"attempts": 10, "changed": false, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}
```

Wireguard is now in the Ubuntu universe repo and in Debian backports.

**Comment by voryzen** [comment]
This is a repeat of issue #129 
Closing this will close #129
