### ISSUE TITLE
Bug: copying bastion public key fails

### ISSUE THREAD

**Issue by robjloranger** [VivumLab/VivumLab#130]
**Describe the bug**
During the deploy task `Copy BastionServer public key to HomeServer` fails with an error:
```
TASK [vivumlab_wireguard : Copy BastionServer public key to HomeServer] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [myserver]: FAILED! => {"changed": false, "msg": "Could not find or access 'fetch/server_public_key'\nSearched in:\n\t/data/roles/vivumlab_wireguard/files/fetch/server_public_key\n\t/data/roles/vivumlab_wireguard/fetch/server_public_key\n\t/data/roles/vivumlab_wireguard/tasks/files/fetch/server_public_key\n\t/data/roles/vivumlab_wireguard/tasks/fetch/server_public_key\n\t/data/files/fetch/server_public_key\n\t/data/fetch/server_public_key on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

**To Reproduce**
1. Server and bastion running Debian 10
2. Configure, enable the bastion in config, then deploy

**Expected behavior**
Key should copy.

**Desktop (please complete the following information):**
 - OS: Debian 10.6
 - Service: n/a
 - Vivumlab Version: v0.3.0

**Comment by voryzen** [comment]
This will need more information.

You'll need to run the same commands with debug=high, and post the output

**Comment by robjloranger** [comment]
how much do you need? I notice that thre are only calls to the local server IP, none to the remote bastion

**Comment by voryzen** [comment]
I have assigned this to you. feel free to contribute, as you see fit
