### ISSUE TITLE
Bug: bastion server broken?

### ISSUE THREAD

**Issue by robjloranger** [VivumLab/VivumLab#131]
**Describe the bug**
While debugging other issues, I have noticed that there is no mention of the bastion server in the ansible plays. With hlos I saw each step perform for both the homeserver and bastion, skipping or changing etc as required.

This suggests something is broken with using a bastion server, unless I'm missing something.

**To Reproduce**
1. Enable bastion in settings
2. Deploy

**Expected behavior**
Setup should be performed as required on the bastion.

**Desktop (please complete the following information):**
 - OS: Debian 10.6
 - Service: n/a
 - Vivumlab Version: v0.3.0

**Comment by robjloranger** [comment]
if true, this would explain #130

**Comment by voryzen** [comment]
it sounds like you may understand the reason for this issue.

I have assigned this to you. feel free to contribute, as you see fit

**Comment by robjloranger** [comment]
I have no idea lol, just that is not working as expected
