### ISSUE TITLE
Feature Request: make pre-commit less invasive

### ISSUE THREAD

**Issue by voryzen** [VivumLab/VivumLab#135]
**Is your feature request related to a problem? Please describe.**
When attempting to run VivumLab without pre-commit installed, VivumLab will give errors

**Describe the solution you'd like**
require pre-commit to be installed when attempting to do anything with git, ..  besides checkout? maybe

**Describe alternatives you've considered**
- making it entirely optional (defeats the purpose)
- removing pre-commit from master

**Additional context**
not applicable

**Comment by robjloranger** [comment]
I think requiring pre-commit is fine, it should just be documented.

**Comment by voryzen** [comment]
It is.

However, not everyone reads the docs
