### ISSUE TITLE
Bug: Linebreak in docs broken

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#136]
**Describe the bug**
`Docker Image: !!! LINK TO DOCKER IMAGE/ DOCKER HUB !!! \ Current Image Version: latest`
line break doesn't work

**Expected behavior**
```
Docker Image: !!! LINK TO DOCKER IMAGE/ DOCKER HUB !!!
Current Image Version: latest
```

**Desktop (please complete the following information):**
 - Vivumlab Version: v0.3.0

**Comment by voryzen** [comment]
is this a travis thing?

**Comment by denis-ev** [comment]
No, no travis thing, should be a markdown thing.

**Comment by voryzen** [comment]
github markdown should work with a backslash or two spaces.
that's all I could find on it

**Comment by denis-ev** [comment]
oh, okay.

Yeah I'm testing that later.
