### ISSUE TITLE
Bug: Clone Config migration config.yml to prod-config.yml task

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#155]
**Describe the bug**
Config is not yet migrated to prod-config.yml

**To Reproduce**
change to dev branch and run `vlab deploy`, a new config is being created.

**Expected behavior**
folder is checked for prod-config.yml and if not found, checks for config.yml then renames config.yml to prod-config.yml

**Desktop (please complete the following information):**
 - Vivumlab Version: dev

**Comment by voryzen** [comment]
This was a little rushed, and wasn't approved by two members.

Maybe it should be reversed, and fixed on another branch
