### ISSUE TITLE
Bug: Net new setup fails with sanity checks on line 134.

### ISSUE THREAD

**Issue by codefriar** [VivumLab/VivumLab#183]
**Describe the bug**
Brand new big sur system. 
Ran vlab config. 
Saw a flutter of warnings about pre-commit not being present per recommendation Ran vlab dev_setup. 
Re-ran vlab config, got 

```
--- Stack trace from shell process 24908 depth=0 -------------
Failed command: pre-commit install --install-hooks > /dev/null 2>&1
Return status: 3

File /Users/kpoorman/src/VivumLab/tasks/SanityChecks.sh, line 138, in Task::check_for_precommit ()
File /Users/kpoorman/src/VivumLab/tasks/SanityChecks.sh, line 11, in Task::sanity_check_local ()
File /Users/kpoorman/src/VivumLab/tasks/Core.sh, line 15, in Task::logo_local ()
File /Users/kpoorman/src/VivumLab/tasks/Config.sh, line 14, in Task::config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
```

**To Reproduce**
1. Fresh checkout of vlab.
1. run vlab config
1. error

**Expected behavior**
it creates a config setup.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  MacOS Big Sur
 - Vivumlab Version: 0.4.0

**Additional context**

**Comment by voryzen** [comment]
Hi mate,

In sanitychecks.sh, find line 138,
```
[ ! -f .git/pre-commit ] || pre-commit install && pre-commit install --install-hooks > /dev/null 2>&1
```
and remove `pre-commit install && `, so it looks like this:
```
[ ! -f .git/pre-commit ] || pre-commit install --install-hooks > /dev/null 2>&1
```
And let me know

**Comment by voryzen** [comment]
If this issue has a fix, can we close it?

@VivumLab/core-team ?
