### ISSUE TITLE
Bug: hardcoded lookups --config-dir not represented

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#258]
**Describe the bug**
`{{lookup('password', './settings/passwords/portus_secret_key_base chars=ascii_letters')}}`

**Expected behavior**
lookup should have a variable for the config dir, to have separate passwords for different config directories
---config-dir=dev should have a lookup like `{{lookup('password', './settings/dev/passwords/portus_secret_key_base chars=ascii_letters')}}`
without it should look like `{{lookup('password', './settings/passwords/portus_secret_key_base chars=ascii_letters')}}`

**Additional context**

**Comment by codefriar** [comment]
fixed by !264
