### ISSUE TITLE
Feature Request: incorporate starship.rs and set MOTD for docker container

### ISSUE THREAD

**Issue by codefriar** [VivumLab/VivumLab#310]
Let's incorporate 

(Starship.rs)[https://starship.rs/] into the docker container, so people can easily and quickly see what branch they're using.

@denis-ev - is there any way to magically set it up so when someone clones, they automatically get the latest release not dev?

Finally, i think we should put a static quick and dirty MOTD together telling people to invoke vlab etc.

**Comment by denis-ev** [comment]
if someone wants to use it, they are not supposed to clone.
I'm trying to get the curl ./launch.sh perfectly working so they will automatically be using the latest version all the time.

I tried adding a MOTD, but had some problems to get it to show up.

**Comment by denis-ev** [comment]
partial fix #314 (adding motd)

**Comment by denis-ev** [comment]
You really want to add starships? I like the idea, but with ./launch.sh they always have the latest, because it always pulls the newest.
As a dev you run -v dev or -v local, then you should know what you are running.

**Comment by codefriar** [comment]
I love starship. I like the color, and data it presents. I imagine it'd be great to put the git hash in the prompt, so that when people file bug reports, we can tell them where to get the specific githash they're using. it's a low priority, make it pretty thing...
