### ISSUE TITLE
Bug: Can't log into the server with a password encrypted ssh key.

### ISSUE THREAD

**Issue by joao-p-marques** [VivumLab/VivumLab#316]
**Describe the bug**
When I pass to the container an ssh key that is password protected, it cannot access it and, thus, the connection to the server fails.

**To Reproduce**
1. Launch the container: `./launch.sh -v dev`
2. Generate a new config: `vlab config new --dev`
3. Run the first deploy: `vlab deploy`.

**Expected behavior**
The playbook should be able to access the server and deploy the services.
 
**Screenshots**

When I try `vlab deploy` I get an error: `Failed to authenticate: private key file is encrypted
Indeed, my ssh key requires a password. 

Another thing I've tried is to install ssh on the vlab container and access manually with `ssh user@IP`. I am prompted for the password, and can access successfully. However, if I then try to run `vlab deploy` again I get `SSH authentication is incorrect`.

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Service: None yet
 - Vivumlab Version: 1.1.0

**Comment by codefriar** [comment]
@denis-ev would something like this work?

**Comment by codefriar** [comment]
https://stackoverflow.com/questions/50277495/how-to-run-an-ansible-playbook-with-a-passphrase-protected-ssh-private-key

**Comment by denis-ev** [comment]
> @denis-ev would something like this work?
> 
> https://stackoverflow.com/questions/50277495/how-to-run-an-ansible-playbook-with-a-passphrase-protected-ssh-private-key

I think I tried and read this too. Might not work with the SSH Key.

This seems to be the only way https://stackoverflow.com/a/51500802/6513529
