### ISSUE TITLE
Bug: Collection Auto-Volumes created wrongly

### ISSUE THREAD

**Issue by joao-p-marques** [VivumLab/VivumLab#317]
**Describe the bug**

According to the playbook, the Collection Auto-Volumes are only created when the `nas_enabled` variable is True (which it isn't by default). https://github.com/VivumLab/VivumLab/blob/fix/dockerfile/roles/vivumlab_deploy/tasks/main.yml#L52

They are also created without specifying the owner and group, which can make them be created with the wrong permissions.

Some services try to mount volumes there. https://github.com/VivumLab/VivumLab/blob/fix/dockerfile/roles/nextcloud/templates/docker-compose.nextcloud.yml.j2#L45
If the directories are not created, they are automatically created by docker with the wrong permissions (root), which leads to runtime errors when the application tries to write there (see screen shot bellow)

**To Reproduce**
1. Generate a config and deploy to the server
2. Enable nextcloud and deploy
3. Try to access nextcloud
4. See the error

**Expected behavior**
The volumes should be previously created with the correct permissions to ensure no errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/38977934/105422788-4035e880-5c3c-11eb-8980-923abed2f626.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33 (laptop) and Debian (server)
 - Service: nextcloud
 - Vivumlab Version: 1.1.0

**Comment by denis-ev** [comment]
Ah interesting, investigating ...
