### ISSUE TITLE
Wrong markdown admonitions

### ISSUE THREAD

**Issue by Yajo** [VivumLab/VivumLab#413]
## Motivation

Admonitions are not properly rendered:

![screenshot-2021-05-16-06-40-03](https://user-images.githubusercontent.com/973709/118386854-5532ef00-b612-11eb-82ef-4a7e7e4517f4.png)

It seems your docs use [mkdocs-material style admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage): https://github.com/VivumLab/VivumLab/blob/1980841efd0f702690f469dcd651cb39b6c48954/website/docs/core/Installation.md#L23-L31

However, you're using docusaurus: https://github.com/VivumLab/VivumLab/blob/1980841efd0f702690f469dcd651cb39b6c48954/website/README.md#L3

## Suggestion

Either use mkdocs or change admonitions to use [docusaurus style](https://docusaurus.io/docs/markdown-features/admonitions).

**Comment by denis-ev** [comment]
Ah yeah, good catch. We switched a while back and still need to update some docs.
