### ISSUE TITLE
Bug: cannot install

### ISSUE THREAD

**Issue by Yajo** [VivumLab/VivumLab#414]
**Describe the bug**
I'm just trying to install vivumlab and it does not work:

<pre>root@90ef2877377d:/data# vlab deploy
<font color="#729FCF">Creating, or updating Config file settings/prod/config.yml</font>
<font color="#4E9A06">Local sanity checks passed.</font>
<font color="#4E9A06">Config file is now, decrypted</font>

PLAY [127.0.0.1] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
<font color="#4E9A06">ok: [127.0.0.1]</font>

TASK [vivumlab_config : Copy VivumLab config file into place] ******************************************************************************
<font color="#C4A000">changed: [127.0.0.1]</font>

TASK [vivumlab_config : Generate Ansible inventory file] ***********************************************************************************
<font color="#4E9A06">ok: [127.0.0.1]</font>

TASK [vivumlab_config : Copy ansible_bash.vars file into place] ****************************************************************************
<font color="#C4A000">changed: [127.0.0.1]</font>

PLAY RECAP *********************************************************************************************************************************
<font color="#C4A000">127.0.0.1</font>                  : <font color="#4E9A06">ok=4   </font> <font color="#C4A000">changed=2   </font> unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

<font color="#4E9A06">ansible-playbook playbook.config.yml -e config_dir=prod -e @decrypted.yml -i inventory finished</font>
<font color="#729FCF">Migration not needed. Config files valid.</font>
<font color="#4E9A06">settings/prod/encrypted.yml saved</font>
<font color="#4E9A06">Config file is now, encrypted</font>
<font color="#729FCF">Deploying Vivumlab</font>

PLAY [Install python (required by Ansible).] ***********************************************************************************************

TASK [Wait for connection if not available, timeout 600 seconds] ***************************************************************************
<font color="#06989A">skipping: [myserver]</font>

PLAY [Setup TOR] ***************************************************************************************************************************

PLAY [Install and Setup server with VivumLab] **********************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
<font color="#EF2929"><b>fatal: [myserver]: UNREACHABLE! =&gt; {&quot;changed&quot;: false, &quot;msg&quot;: &quot;SSH password was requested, but none specified&quot;, &quot;unreachable&quot;: true}</b></font>

PLAY RECAP *********************************************************************************************************************************
<font color="#CC0000">myserver</font>                   : ok=0    changed=0    <font color="#EF2929"><b>unreachable=1   </b></font> failed=0    <font color="#06989A">skipped=1   </font> rescued=0    ignored=0   

<font color="#CC0000">Ansible Playbook command returned with an error code.</font>
<font color="#CC0000">Exception is: Command ansible-playbook playbook.vivumlab.yml -e @settings/prod/.y36eH9JGJGQ6v-aoQ4nnfg.yml --skip-tags tor --skip-tags bastion -e config_dir=prod -i inventory returned non-zero exit status 4</font>
</pre>

Note: I'm using a VM to test it, and inside the VM I'm trying to deploy locally.

**To Reproduce**
1. 

   ```
   git clone --branch dev https://github.com/VivumLab/VivumLab.git
   cd VivumLab
   ./launch.sh -v dev
   vlab deploy

   ```

**Expected behavior**
According to homepage, it should deploy

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Service: none yet
 - Vivumlab Version: not sure on how to get that...

**Additional context**
I tried with the stable branch first, but it also failed... 😭

**Comment by codefriar** [comment]
@Yajo - this error's cause is here:
```
fatal: [myserver]: UNREACHABLE! => {"changed": false, "msg": "SSH password was requested, but none specified", "unreachable": true}
```

which means you've not set your ssh password.

**Comment by Yajo** [comment]
Weird... I typed it like twice during the setup. 🤔
