### ISSUE TITLE
Bug: Revert your illegal license.

### ISSUE THREAD

**Issue by NickBusey** [VivumLab/VivumLab#526]
You have once again changed the Copyright from my name. This is forked from HomelabOS, an MIT project with a LICENSE file, that you are currently in violation of.

Place the original copyright back, and do not remove it again, or legal action will be pending.

This is the commit where you reverted it back after last time I asked. https://github.com/VivumLab/VivumLab/blob/be4cb11be7add169e2043c6dc0c92b75acdf2cd1/LICENSE

Here is where you originally state it is forked from HomelabOS. https://github.com/VivumLab/VivumLab/blob/be4cb11be7add169e2043c6dc0c92b75acdf2cd1/LICENSE

You are not allowed to just renamed the license to `HomeLabOS License`.

This is the LICENSE file for this entire project. This is now Open Source works.

**Comment by NickBusey** [comment]
Apparently this is legal. I think it's lame, but you do you.

**Comment by voryzen** [comment]
You are checking us out, mate.
Any issues, feel free to contact us.

**Comment by NickBusey** [comment]
I still don't think it actually is legal, hence why I deleted it. Have fun.

**Comment by voryzen** [comment]
No worries, mate.
Its good to see you're doing well.

Thanks again for checking us out.
Any issues, feel free to contact us.
